name: auto_check_notice
on: 
  schedule:
    - cron: '1 1/2 * * *'   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and redis and run #安装requests模块
      run: |
        pip install requests redis
        python check_run.py

