name: auto_check_notice
on: 
  push:
    branches:
      - main
      
  schedule:
    - cron: '*/10 * * * *'   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and redis and run #安装requests模块
      env: 
        #github的账号信息
        TG_TOKEN: ${{ secrets.TG_TOKEN }} 
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        REDIS_PWD: ${{ secrets.REDIS_PWD }}
      run: |
        pip install requests redis
        python check_run.py

