name: auto_check_notice
on:
  push:
  schedule:
    - cron: '*/30 * * * *'   
jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and redis and run #安装requests模块
      # env: 
        #github的账号信息
        #
        #   TG_TOKEN: ${{ secrets.TG_TOKEN }} 
        #TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        #REDIS_PWD: ${{ secrets.REDIS_PWD }}
      run: |
        pip install redis
        pip install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master
    - name: run check_run and tweets_tg_notices
      env:
         TG_TOKEN: ${{ secrets.TG_TOKEN }}
         TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
         REDIS_PWD: ${{ secrets.REDIS_PWD }}
         CLIENT_ID: ${{ secrets.CLIENT_ID }}
         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
         MAIL_REFRESH_TOKEN: ${{ secrets.MAIL_REFRESH_TOKEN }}
         SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
         HEARTBEAT: ${{ secrets.GITACTION_HEARTBEAT }}
      run: |
        python check_run.py
        python tweets_tg_notice.py
        python update_ms_token.py

