name: auto_check_cron
on: 
  schedule:
    - cron: '*/6 * * * *'
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and nacl #安装requests模块
      run: |
        pip install requests
        echo run
